<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>ZipNShip.Core</PackageId>
		<Version>1.0.0</Version>
		<Authors>Sameer Ahmed</Authors>
		<Description>ZipNShip core + all plugins</Description>
	</PropertyGroup>
</Project>
